drop table if exists supplier;
drop table if exists item;
drop table if exists supplier_order;


create table supplier (
    id integer primary key generated by default as identity,
    supplier_name text not null,
    phone text,
    city text
);

create table item (
    id integer primary key generated by default as identity,
    item_name text not null,
    unit text,
    unit_cost numeric,
    supplier integer references supplier(id) on delete set null
);

create table supplier_order (
    id integer primary key generated by default as identity,
    order_date date default now(),
    item integer references item(id) on delete cascade not null,
    amount numeric,
    total_cost numeric,
    shipping_status text
);